Repository srobo/j5, pull requests merged in 2019-02, with the labels that each got.

#70 Add a Battery sensor
  j5/components/__init__.py
  j5/components/battery_sensor.py
  tests/components/test_battery_sensor.py
Labels: enhancement

#40 Add Piezo component
  j5/components/__init__.py
  j5/components/piezo.py
  tests/components/test_piezo.py
Labels: enhancement

#67 [DOCS]: Add some philosophy.
  docs/concepts/philosophy.rst
Labels: documentation

#111 Add an abstract discover method to Backend
  j5/backends/base.py
  j5/backends/dummy/demo.py
  tests/backends/test_base.py
  tests/boards/j5/test_demo.py
  tests/boards/test_base.py
Labels: enhancement

#114 Split BackendMeta.__new__ into more understandable functions.
  j5/backends/base.py
Labels: refactor

#126 Fix ButtonInterface.wait_until_button_pressed return type
  j5/components/button.py
Labels: bug

#127 Add a development guide
  docs/development/index.rst
  docs/index.rst
Labels: documentation

#128 Class structure documentation
  README.md
  docs/concepts/structure.rst
  docs/conf.py
  j5.svg
Labels: documentation

#119 Input validation for piezo's buzz method and improved test coverage
  j5/components/piezo.py
  tests/components/test_piezo.py
Labels: bug

#136 Add lock to BaseRobot to prevent multiple robot processes.
  j5/base_robot.py
  tests/test_stack.py
Labels: enhancement

#145 Add Typing and Education Troves for PyPI
  setup.py
Labels: documentation
