Repository srobo/j5, pull requests merged in 2019-04, with the labels that each got.

#212 Motors
  j5/components/__init__.py
  j5/components/motor.py
  tests/components/test_motor.py
Labels: enhancement

#204 Console environment
  j5/backends/console/__init__.py
  j5/backends/console/env.py
  j5/backends/console/sr/__init__.py
  j5/backends/console/sr/v4/__init__.py
  j5/backends/console/sr/v4/power_board.py
  tests/backends/console/__init__.py
  tests/backends/console/sr/__init__.py
  tests/backends/console/sr/v4/__init__.py
  tests/backends/console/sr/v4/test_power_board.py
  tests/backends/console/test_env.py
Labels: enhancement

#221 Replace 3.7 with 3.6 in the docs as we support both now
  docs/development/index.rst
  docs/usage/installation.rst
Labels: documentation

#225 Correct version and copyright for docs
  docs/conf.py
  j5/__init__.py
Labels: documentation

#222 Replace pipenv with poetry for development
  docs/development/index.rst
Labels: documentation

#223 Fix an incorrect type on the Power Board firmware version
  j5/backends/hardware/sr/v4/power_board.py
  tests/backends/hardware/sr/v4/test_power_board.py
Labels: typing

#219 Minor docs improvements
  docs/Makefile
  docs/conf.py
  docs/source/j5.backends.dummy.rst
  docs/source/j5.backends.hardware.rst
  docs/source/j5.backends.hardware.sr.rst
  docs/source/j5.backends.hardware.sr.v4.rst
  docs/source/j5.backends.rst
  docs/source/j5.boards.j5.rst
  docs/source/j5.boards.rst
  docs/source/j5.boards.sr.rst
  docs/source/j5.boards.sr.v4.rst
  docs/source/j5.components.rst
  docs/source/j5.rst
  docs/source/modules.rst
Labels: documentation

#233 Use sets instead of lists for unordered collections
  j5/backends/backend.py
  j5/backends/console/sr/v4/power_board.py
  j5/backends/hardware/sr/v4/power_board.py
  j5/boards/board.py
  j5/boards/sr/v4/power_board.py
  tests/backends/hardware/sr/v4/test_power_board.py
  tests/backends/test_backend.py
  tests/boards/sr/v4/test_power_board.py
  tests/boards/test_board.py
  tests/components/test_battery_sensor.py
  tests/components/test_button.py
  tests/components/test_gpio_pin.py
  tests/components/test_led.py
  tests/components/test_motor.py
  tests/components/test_piezo.py
  tests/components/test_power_output.py
  tests/components/test_servo.py
Labels: refactor

#242 Add a quick start guide to the docs.
  docs/usage/quickstart.rst
Labels: documentation

#239 Add links to git tutorials to development guide.
  docs/development/getting-started.rst
  docs/development/index.rst
Labels: documentation

#243 Use floating point numbers for Piezo
  j5/backends/console/sr/v4/power_board.py
  j5/backends/hardware/sr/v4/power_board.py
  j5/components/piezo.py
  tests/backends/console/sr/v4/test_power_board.py
  tests/components/test_piezo.py
Labels: enhancement

#258 Add hardware docs for the SR v4 motor board.
  docs/hardware/srobo/LICENSE.rst
  docs/hardware/srobo/img/mcv4.png
  docs/hardware/srobo/img/mcv4_diagram.svg
  docs/hardware/srobo/index.rst
  docs/hardware/srobo/mbv4.rst
  docs/hardware/srobo/pbv4.rst
  docs/hardware/srobo/sbv4.rst
Labels: documentation

#261 Boardgroup Improvements
  j5/boards/board.py
  tests/boards/test_board.py
Labels: enhancement, typing

#272 Add a comparison between j5, existing APIs and ROS
  docs/concepts/comparison.rst
  docs/concepts/index.rst
Labels: documentation
