Repository srobo/j5, pull requests merged in 2019-03, with the labels that each got.

#138 GPIO Pin Component
  j5/components/__init__.py
  j5/components/base.py
  j5/components/gpio_pin.py
  tests/components/test_gpio_pin.py
Labels: enhancement

#129 Consolidate j5 version
  docs/conf.py
  j5/__init__.py
  setup.py
Labels: enhancement

#93 [WIP] SR v4 Power Board
  j5/backends/__init__.py
  j5/backends/base.py
  j5/backends/hardware/__init__.py
  j5/backends/hardware/env.py
  j5/backends/hardware/sr/__init__.py
  j5/backends/hardware/sr/v4/__init__.py
  j5/backends/hardware/sr/v4/power_board.py
  j5/boards/sr/__init__.py
  j5/boards/sr/v4/__init__.py
  j5/boards/sr/v4/power_board.py
  j5/components/__init__.py
  j5/components/piezo.py
  j5/components/power_output.py
  mypy.ini
  shell.nix
  stubs/usb/__init__.pyi
  stubs/usb/core.pyi
  stubs/usb/util.pyi
  tests/backends/hardware/__init__.py
  tests/backends/hardware/sr/__init__.py
  tests/backends/hardware/sr/v4/__init__.py
  tests/backends/hardware/sr/v4/test_power_board.py
  tests/backends/hardware/test_env.py
  tests/boards/sr/__init__.py
  tests/boards/sr/v4/__init__.py
  tests/boards/sr/v4/test_power_board.py
  tests/components/test_piezo.py
  tests_hw/__init__.py
  tests_hw/test_power_board.py
Labels: enhancement

#174 Update shell.nix
  shell.nix
Labels: bug

#176 shell.nix: use a more up-to-date URL in workaround command
  shell.nix
Labels: bug

#190 Add graphviz to Nix environment
  shell.nix
Labels: bug

#193 Add __str__ to BoardGroup and fix type.
  j5/boards/board.py
  tests/boards/test_board.py
Labels: enhancement, typing

#195 Backend refactor
  j5/backends/backend.py
  j5/backends/hardware/sr/v4/power_board.py
  j5/boards/board.py
  j5/boards/sr/v4/power_board.py
  j5/components/battery_sensor.py
  j5/components/button.py
  j5/components/gpio_pin.py
  j5/components/led.py
  j5/components/piezo.py
  j5/components/power_output.py
  j5/components/servo.py
  tests/backends/hardware/sr/v4/test_power_board.py
  tests/backends/test_backend.py
  tests/boards/sr/v4/test_power_board.py
  tests/boards/test_board.py
  tests/components/test_battery_sensor.py
  tests/components/test_button.py
  tests/components/test_gpio_pin.py
  tests/components/test_led.py
  tests/components/test_piezo.py
  tests/components/test_power_output.py
  tests/components/test_servo.py
Labels: refactor

#210 Typecheck the tests
  .circleci/config.yml
  Makefile
  stubs/pytest.pyi
  tests/backends/hardware/sr/v4/test_power_board.py
  tests/backends/hardware/test_env.py
  tests/backends/test_backend.py
  tests/boards/sr/v4/test_power_board.py
  tests/boards/test_board.py
  tests/components/test_battery_sensor.py
  tests/components/test_button.py
  tests/components/test_gpio_pin.py
  tests/components/test_led.py
  tests/components/test_piezo.py
  tests/components/test_power_output.py
  tests/components/test_servo.py
  tests/test_smoke.py
  tests/test_stack.py
Labels: refactor
