Repository srobo/j5, pull requests merged in 2019-06, with the labels that each got.

#293 Add minimal board definition for Arduino Uno
  j5/boards/arduino/__init__.py
  j5/boards/arduino/uno.py
  tests/boards/arduino/__init__.py
  tests/boards/arduino/test_uno.py
Labels: enhancement

#299 Ultrasound Support
  j5/boards/arduino/uno.py
  j5/components/__init__.py
  j5/components/component.py
  j5/components/derived/__init__.py
  j5/components/derived/ultrasound.py
  j5/components/gpio_pin.py
  tests/components/derived/__init__.py
  tests/components/derived/test_ultrasound_sensor.py
  tests/components/test_gpio_pin.py
Labels: enhancement

#309 Uncomment servo init
  j5/backends/hardware/sr/v4/servo_board.py
Labels: bug

#319 update_boards: re-use existing _boards dictionary
  j5/boards/board.py
  tests/boards/test_board.py
Labels: refactor, typing
